name: Rust

on:
  push:
    branches: [ '*' ]
    
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build -r

    - name: Run benchmark I
      run: cargo run -r

    - name: Run benchmark II
      run: cargo run -r

    - name: Run benchmark III
      run: cargo run -r
